Add mentor details
anitab-org/open-source-day pull request #25
Opened 2021-07-06 06:49 UTC by Kajol-Kumari

### Description

### Type of Change:

- Code

**Code/Quality Assurance Only**
- UI enhancements on Mentors Page

### How Has This Been Tested?
Locally, attaching the recording for ref -

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2021-07-06 19:05 UTC, renana commented
Please remove all changes made to files in '_site' folder.

2021-07-06 19:08 UTC, renana commented on _site/open-source-day-2021-summer-mentors/index.html
> +<div itemscope="" itemtype="https://schema.org/Person" class="mentor-details">
`class="mentor-details"` needs to be added to` _includes/mentor-profile.html` instead of here.

2021-07-06 19:09 UTC, renana commented on _includes/mentor-profile.html
> +<div itemscope itemtype="https://schema.org/Person">
You should add `class="mentor-details"` to here instead to the generated file.

2021-07-06 19:13 UTC, renana commented
Please fix the images under `assets/images/mentors` or open a pull request against the fork it was taken from. We can merge this to the main repo without it being published and the images still need to be fixed.
**The requested change here is to make sure all images have the same height and width so they will appear uniformed.**

2021-07-06 19:33 UTC, renana requested changes

2021-07-06 19:33 UTC, renana commented on _site/open-source-day-2021-summer-mentors/index.html
> +    .mentor-details {
This change should be moved to `assets/css/main.scss`

2021-07-08 10:30 UTC, Kajol-Kumari commented
Hey @renana have made a fresh PR against the `mentors-directory` branch, hence closing this PR. Please checkout https://github.com/anitab-org/open-source-day/pull/28

2021-07-08 10:30 UTC, closed without merging